name: flutter_testing
description: Learn Testing.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lorem: ^2.0.0
  mocktail: ^1.0.4
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # mocktail: ^0.3.0

flutter:
  uses-material-design: true
